amcl:
  ros__parameters:
    alpha1: 0.05
    alpha2: 0.05
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.20
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: 0.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom_rf2o"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 3
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 2.0
    update_min_a: 0.08
    update_min_d: 0.08
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: "scan_filtered"
    set_initial_pose: true
    initial_pose: {x: 0.0, y: 0.0, z: 0.0, yaw: 0.0}

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom_rf2o
    odom_frame: odom_rf2o
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 2000.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    error_code_names: [compute_path_error_code, follow_path_error_code]

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 15.0
    min_x_velocity_threshold: 0.02
    min_y_velocity_threshold: 0.02
    min_theta_velocity_threshold: 0.02
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.03
      movement_time_allowance: 10.0

    goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.15

    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"


      angular_dist_threshold: 0.2
      forward_sampling_distance: 0.6
      rotate_to_heading_angular_vel: 0.5
      rotate_to_goal_heading: true
      rotate_to_heading_once: true

     
      desired_linear_vel: 0.25
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.5
      lookahead_time: 1.5
      use_velocity_scaled_lookahead_dist: true
      rotate_to_heading_lookahead_dist: 0.8
      transform_tolerance: 0.2
      use_interpolation: true
      max_allowed_time_to_collision: 3.0
      allow_reversing: true

     
      use_rotate_to_heading: true
      use_shortest_path: true
      allow_omnidirectional_motion: true
      regulate_velocity_scale: 1.0
      linear_vel_x_max: 0.35
      linear_vel_y_max: 0.35
      min_vel_x: -0.35
      min_vel_y: -0.35
      max_vel_theta: 0.6
      min_vel_theta: -0.6
      acc_lim_x: 0.4
      acc_lim_y: 0.4
      acc_lim_theta: 0.8
      decel_lim_x: -0.4
      decel_lim_y: -0.4
      decel_lim_theta: -0.8


      approach_velocity_scaling: 0.6
      stop_on_failure: false
      use_collision_detection: true
      motion_model: "Omni"
      visualize: true

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 8.0
      publish_frequency: 5.0
      global_frame: odom_rf2o
      robot_base_frame: base_footprint
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.15
      transform_tolerance: 2.0
      plugins: ["voxel_layer", "inflation_layer", "static_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.18
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        observation_sources: scan
        scan:
          topic: /scan_filtered
          data_type: "LaserScan"
          clearing: True
          marking: True
          raytrace_max_range: 3.0
          obstacle_max_range: 2.5
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 2.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_footprint
      robot_radius: 0.15
      resolution: 0.05
      track_unknown_space: true
      transform_tolerance: 2.0
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan_filtered
          data_type: "LaserScan"
          clearing: True
          marking: True
          raytrace_max_range: 3.0
          obstacle_max_range: 2.5
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.3

map_server:
  ros__parameters:
    yaml_filename: /home/rasp/map.yaml
    topic_name: "map"
    frame_id: "map"

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    costmap_update_timeout: 1.0
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 1.0
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    wait:
      plugin: "nav2_behaviors::Wait"
    local_frame: odom_rf2o
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 2.0
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

collision_monitor:
  ros__parameters:
    cmd_vel_in_topic: "cmd_vel_nav"
    cmd_vel_out_topic: "cmd_vel_safety"

velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 30.0
    input_cmd_vel_topic: "cmd_vel_safety"
    smoothed_cmd_vel_topic: "cmd_vel_smoothed"
    odom_topic: "odom_rf2o"
    max_velocity: [0.350, 0.350, 1.20]
    min_velocity: [-0.35, -0.35, -1.2]
    max_accel: [0.300, 0.300, 10.0]
    max_decel: [-0.30, -0.30, -1.0]
    deadband_velocity: [0.0, 0.05, 0.03]